spring:
  application:
    name: Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mansi-Kain/MicroService-config
          clone-on-start: true

server:
  port: 8085
